### ISSUE TITLE
Automatically calculate bank holidays

### ISSUE THREAD

**Issue by julienw** [julienw/forms-extension#1]

**Comment by julienw** [comment]
There are 2 possible ways.

Most complicated is migrate all date calculations to moment.js and then use https://github.com/DepthFrance/moment-ferie-fr; I'd like to do unit tests before migrating to moment.js to ensure we don't regress.

Easiest is to port https://github.com/DepthFrance/moment-ferie-fr/blob/master/moment-ferie-fr.js to using native Date instead :)

**Comment by Natim** [comment]
Was done in #9

**Comment by julienw** [comment]
yep
