### ISSUE TITLE
We shouldn't decrement "hours" for "JF" type holidays

### ISSUE THREAD

**Issue by julienw** [julienw/forms-extension#10]
see https://github.com/julienw/forms-extension/blob/e89efd221712b2aa2377314940b6312a42db37b7/src/data/calendar.js#L137-L140

I don't think the PTO tool includes hours for JF. (but we should check it first)

**Comment by Natim** [comment]
![example-with-november-1st](https://cloud.githubusercontent.com/assets/229453/22017919/91551006-dcac-11e6-9b04-d44a59d641f1.png)

It doesn't seems to be the case.

**Comment by Natim** [comment]
I also tryied I may to see if US holidays were taken into account but it is not the case either. Only the week-end doesn't count.

**Comment by julienw** [comment]
OK I'm surprised, I definitely remember some days being in a "disabled" state sometimes.

But you're right, I looked in a previous holiday I had during August 15th and the hours are actually used.
