### ISSUE TITLE
Use debounce instead of throttle

### ISSUE THREAD

**Issue by julienw** [julienw/forms-extension#12]
In https://github.com/julienw/forms-extension/blob/e89efd221712b2aa2377314940b6312a42db37b7/src/data/form-interaction.js#L13 we really want a debounce instead of a throttle after the latest changes. And then we can decrease the delay to eg 500.

**Comment by Natim** [comment]
This looks to be a great fit: https://davidwalsh.name/javascript-debounce-function

**Comment by Natim** [comment]
Even simpler:

```
var timeout;
function debounce(event) {
  if (timeout) {
    clearTimeout(timeout);
  }
  timeout = setTimeout(function() {
    storeNote(event.target.value);
  }, 500);
}
```

**Comment by julienw** [comment]
yep, looks good :)

**Comment by julienw** [comment]
I think the hack in #41 makes this unnecessary now.
