### ISSUE TITLE
Recognize half day holidays

### ISSUE THREAD

**Issue by julienw** [julienw/forms-extension#2]
In the PTO application, we have "4" in the column for "hours".

**Comment by pnkfelix** [comment]
(sort of related to #8 ...)

**Comment by julienw** [comment]
Note you can change it manually in the form itself, using "0.5R" for a half day RTT, or 0.5CP for a half day annual leave.

**Comment by Natim** [comment]
This was fixed by #9

**Comment by julienw** [comment]
done
