### ISSUE TITLE
The month label was wrong while trying to print the June panel in July.

### ISSUE THREAD

**Issue by Natim** [julienw/forms-extension#24]
I have no idea yet why.

![month](https://user-images.githubusercontent.com/229453/27850697-33b789c2-610b-11e7-8dda-182845a4c4e3.png)

**Comment by Natim** [comment]
Cannot reproduce. I changed back to the `Europe/Paris` timezone on my computer and it is back working.

**Comment by julienw** [comment]
yeah it worked for me too.
