### ISSUE TITLE
is the right hand column supposed to be counting days, or hours?

### ISSUE THREAD

**Issue by pnkfelix** [julienw/forms-extension#8]
I just noticed that the right hand column in the generated sheet is printing out days.

For some reason I had thought that was supposed to be filled in with a number of hours of PTO for that week, not days.

(This should be simple to fix, if it is indeed a bug.  I just am not sure what is supposed to be there.)

**Comment by julienw** [comment]
very good question indeed :) I'm not sure, it's not precised in the previous form. I'll need to ask Doris.
I'm pretty sure I used days and not hours in my own :D

**Comment by Natim** [comment]
This should be closed now.

**Comment by julienw** [comment]
right

**Comment by julienw** [comment]
(obsoleted by the new form)
